"""empty message

Revision ID: 267488a2a76a
Revises: 
Create Date: 2022-05-22 15:24:10.182672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267488a2a76a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('add', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'add')
    # ### end Alembic commands ###
